CREATE PACKAGE pkg_ventas AS
    
    PROCEDURE TP6_EJ3(idVendedor IN NUMBER, monto IN NUMBER);
    FUNCTION CALCULA_FUNC(p_a IN NUMBER DEFAULT 0, p_b IN NUMBER DEFAULT 0) RETURN NUMBER;
    
    
    
END;