CREATE USER USR1 IDENTIFIED BY usr1 
	DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP 
	PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT TO USR1;
GRANT UNLIMITED TABLESPACE TO USR1;
GRANT CREATE PROCEDURE TO USR1;
GRANT CREATE TRIGGER TO USR1;
ALTER USER USR1 DEFAULT ROLE ALL;
